title: My Ideas Blog
author: Your Name
description: Sharing thoughts, experiments, and personal insights.
baseurl: "/blog"
url: "https://barbierimauro.github.io"
theme: null
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-feed